bug(courseHeader): Fix 404 on completion; add 'Öffnen' button for fin…
e-Learning-by-SSE/nm-self-learning pull request #144
Opened 2024-04-08 12:07 UTC by palfner-sse

Closes #134

2024-04-08 12:32 UTC, spark-sse commented
bitte kurz beschreiben warum der bug aufgetaucht ist; damit das nicht verloren geht

2024-04-15 11:06 UTC, palfner-sse commented
Das Problem tritt auf, da der Button so konfiguriert ist, dass er automatisch die zuletzt abgeschlossene Einheit +1 öffnet. Wenn jedoch alle Einheiten abgeschlossen sind, versucht er, auf eine nicht vorhandene Einheit zu verweisen. Um dieses Problem zu beheben, wird nun die erste Einheit erneut geöffnet, falls dieser Fall eintritt. Des Weiteren heißt der Button dann Öffnen.

2024-06-11 18:55 UTC, spark-sse requested changes
ich werde die änderungen direkt einbauen

2024-06-11 18:55 UTC, spark-sse commented on apps/site/pages/courses/[courseSlug]/index.tsx
> +						((completion?.courseCompletion.completedLessonCount ?? 0) >=
duplicate von `completion?.courseCompletion.completedLessonCount ?? 0` an mehreren stellen

2024-06-11 18:55 UTC, spark-sse commented on apps/site/pages/courses/[courseSlug]/index.tsx
> +								href={`/courses/${course.slug}/${content[0].content[0].slug}`}
`content[0].content[0]` unklar wofür das steht

2024-06-11 18:55 UTC, spark-sse commented on apps/site/pages/courses/[courseSlug]/index.tsx
> +						))}
es kann schon in ordnung sein, dass mehrere Link elemente zurückgegeben werden. Da beide Link elemente allerdings beide das selbe CSS design mit dem gleichen PlayIcon haben, wirkt es eher wie ein duplicate. 

Folgendes könnte ein beispiel sein (wobei hier der tradeoff die hohe komplexität der Start/Öffnen/Fortfahren ist): 

```suggestion

					{isEnrolled && (
						<Link
							href={`/courses/${course.slug}/${
								nextLessonSlug ?? firstLessonFromChapter.slug
							}`}
							className="btn-primary"
						>
							<span>
								{nextLessonSlug
									? lessonCompletionCount === 0
										? "Starten"
										: "Fortfahren"
									: "Öffnen"}
							</span>
							<PlayIcon className="h-5" />
						</Link>
					)}

``` 

Ich empfinde die Lösung aber als mehr straight forward und gleichzeitig lesbarer

2024-06-11 18:55 UTC, spark-sse commented on apps/site/pages/courses/[courseSlug]/index.tsx
> +								href={`/courses/${course.slug}/${nextLessonSlug}`}
wenn ich das richtig sehe ist nextLessonSlug wenn completion falsy ist, oder wenn all chapter einer lesson fertig  sind. aka alle einheiten sind fertig.

2024-06-17 10:20 UTC, palfner-sse commented
Dann kann das Gemerget werden, wenn du die Änderungen gemacht hast?

2024-07-30 14:52 UTC, spark-sse commented
test fehlt noch

2024-08-01 08:26 UTC, spark-sse approved these changes

2024-08-06 11:04 UTC, merged