Chore/130 refactor infrastructure to improve maintainability
e-Learning-by-SSE/nm-self-learning pull request #150
Opened 2024-05-13 08:26 UTC by palfner-sse

2024-06-17 11:53 UTC, spark-sse commented
behebt das login findMany problem auf dem staging

2024-08-03 13:06 UTC, lukas-png requested changes

2024-09-05 15:57 UTC, palfner-sse commented on libs/data-access/database/src/lib/demo/seed-java-demo-skills.ts
>  	}
Gute Idee verbessere ich mal.

2024-09-05 16:21 UTC, palfner-sse commented on libs/data-access/database/src/lib/demo/seed-java-demo-skills.ts
>  	}
Hab das noch mal angeschaut. Mathematik und Psychologie sind ernsthaft Daten, die dablieben sollen, auch wenn man im nicht im DEV Mode ist. Java und React sind nur Demodaten, daher sind die im Demo Ordner.

2024-09-05 16:25 UTC, palfner-sse commented on libs/data-access/database/src/lib/license.ts
> +			"Nur für die interne Verwendung an der Universität Hildesheim (Moodle, Selflernplattform, Handreichungen) erlaubt. Weitere Verwendung, Anpassung und Verbreitung sind nicht gestattet.",
Das eine sind die Demo Lizenzen und das andere ist der Datentyp.

2024-09-09 15:37 UTC, spark-sse approved these changes

2024-09-09 15:38 UTC, merged