Feat/154 seite für einstellungen
e-Learning-by-SSE/nm-self-learning pull request #166
Opened 2024-06-13 19:18 UTC by lukas-png

2024-07-18 11:36 UTC, spark-sse requested changes

2024-07-18 14:14 UTC, lukas-png commented on libs/data-access/api/src/lib/trpc/routers/settings.router.ts
> +		if (ctx.user.role === "ADMIN") return null;
Ich möchte aber genau das Gegenteil. Also das admins das nicht benutzten

2024-07-18 14:15 UTC, lukas-png commented on apps/site/pages/user-settings/index.tsx
> +		</>
Ich kann den Speichern button für den Dialog und die Seite rausnehmen

2024-08-05 11:35 UTC, spark-sse commented on libs/data-access/api/src/lib/trpc/routers/settings.router.ts
> +		if (ctx.user.role === "ADMIN") return null;
auch admins können lernen

2024-08-05 14:37 UTC, merged

2024-10-14 13:26 UTC, spark-sse commented
#192