Feat/einstellungen und dashboard
e-Learning-by-SSE/nm-self-learning pull request #194
Opened 2024-09-02 12:20 UTC by lukas-png

2024-09-02 14:14 UTC, spark-sse requested changes

2024-09-02 14:14 UTC, spark-sse commented on libs/feature/settings/src/lib/settings-form/student-delete-form.tsx
> +function generateDeletionTooltip(deletionInfo: string[]): string {
wenn die methode vorhanden bleibt: schlage hier `deleteTooltipDisplayText` als methodenname vor.

2024-09-02 14:14 UTC, spark-sse commented on libs/feature/settings/src/lib/settings-form/student-delete-form.tsx
> +}
- Student Delete Form und Student Delete Dialog wirken sehr eng gekoppelt und sie sollten vermutlich zusammenhängender gedacht und implementiert werden (zb in der selben datei). 

- wenn die delete logik ausgelagert wird, würde ich empfehlen dass onClose = deleteUser ist. 
- wir hatten die Gespräche bereits. Macht dispatchDialog die Dinge hier wirklich einfacher?

2024-09-02 14:14 UTC, spark-sse commented on libs/feature/settings/src/lib/settings-form/student-delete-form.tsx
> +}
die struktur ist okay, allerdings für den zweck deutlich zu überladen. Es geht hier nur um das Anzeigen eines Tooltips, ohne inhärente Logik. 

Vorschlag ist 


```

function partialDeleteTooltipDisplayText() {
	return "profile information, account settings, saved preferences, ";
}

function fullDeleteTooltipDisplayText() {
	return `${partialDeleteTooltipDisplayText()} created courses, created lessons, skill repositorys`;
}
```

und dann direkt in der Form:

```
<Tooltip title={partialDeleteTooltipDisplayText}>
    <QuestionMarkTooltip tooltipText="Here you can delete all your data." />
</Tooltip>
......
<Tooltip title={fullDeleteTooltipDisplayText}>
    <QuestionMarkTooltip tooltipText="Here you can delete all your data." />
</Tooltip>
```

2024-09-03 09:00 UTC, lukas-png commented on libs/data-access/database/prisma/schema.prisma
>    ownerId       String
ist halt wegen der migration schwierig

2024-09-08 15:41 UTC, lukas-png commented on libs/feature/settings/src/lib/settings-dialog/student-delete-dialog.tsx
> +import { ReactComponent as StatisticSvg } from "../../../../../../apps/site/svg/statistic.svg";
dort werden momentan alle SVG gespeichert. Man könnte sonst überlegen den SVG Speicher zu verschieben

2024-09-09 10:29 UTC, spark-sse commented on libs/feature/settings/src/lib/settings-dialog/student-delete-dialog.tsx
> +import { ReactComponent as StatisticSvg } from "../../../../../../apps/site/svg/statistic.svg";
hab jetzt eine lib "ui-static" erstellt. Für andere namen und orte der lib bin ich offen

2024-09-11 19:02 UTC, spark-sse requested changes

2024-09-11 19:02 UTC, spark-sse commented on libs/feature/settings/src/lib/settings-form/student-delete-form.tsx
> +	}
guard drum herum bauen? Gibt ja ein AuthorizedGuard der quasi das prüft

2024-09-11 19:02 UTC, spark-sse commented on libs/feature/settings/src/lib/settings-form/student-delete-form.tsx
> +	const { mutateAsync: deleteOnlyMe } = trpc.me.deleteMe.useMutation();
`deleteMe`, "only" bringt kein mehrwert

2024-09-11 19:02 UTC, spark-sse commented on apps/site/pages/user-settings/index.tsx
> +			<StudentDeleteForm />
kann man so machen, aber ich finds immer sympatisch wenn das overall styling und position (quasi das äußere div) hiermit auch noch drin ist.

2024-09-11 19:02 UTC, spark-sse commented on apps/site/pages/dashboard/index.tsx
> +}
sollte zukünftig in LTB library. bitte dran denken

2024-09-12 08:20 UTC, lukas-png commented on libs/feature/settings/src/lib/settings-form/student-delete-form.tsx
> +				}}
Geht leider nicht

2024-09-12 08:36 UTC, lukas-png commented on libs/feature/settings/src/lib/settings-form/student-delete-form.tsx
> +	}
Um die Settings Page gibt es schon eine Auth guard. Der User kann halt null sein, deshalb prüfe ich das. Also die useRequiredSession kann undefined zurückgeben

2024-09-12 08:55 UTC, lukas-png commented on apps/site/pages/user-settings/index.tsx
> +			<StudentDeleteForm />
<CenteredSection className="bg-gray-50"> das ist ja das äußere div

2024-09-12 08:55 UTC, lukas-png commented on apps/site/pages/user-settings/index.tsx
> +			<StudentDeleteForm />
also centered div

2024-09-12 10:04 UTC, spark-sse commented on libs/feature/settings/src/lib/settings-form/student-delete-form.tsx
> +	const { mutateAsync: deleteOnlyMe } = trpc.me.deleteMe.useMutation();
nach wie for aktuell bei der mutateAsync

2024-09-12 10:10 UTC, spark-sse commented on libs/feature/settings/src/lib/settings-form/student-delete-form.tsx
> +	}
AuthGuard hab ich nicht gefunden, aber nein, es ist nicht korrekt das name null sein kann. Das liegt dran, weil der lib die type information aus der index.d.ts fehlt

2024-09-12 13:46 UTC, merged

2024-09-27 08:31 UTC, spark-sse commented
Verstehe. Kannst du das einmal dokumentieren.

Also warum man dort trz nochmal auf Null prüft? (zB should not happen 
normally because authGuard is in place; but authguard is clientside)


Am 12.09.2024 um 10:36 schrieb lukas-png:
> @lukas-png commented on this pull request.
>
>
>
>> +	const user = session.data?.user;
> +	if (!user) {
> +		return null;
> +	}
>
> Um die Settings Page gibt es schon eine Auth guard. Der User kann halt null sein, deshalb prüfe ich das. Also die useRequiredSession kann undefined zurückgeben
>

2024-09-27 08:32 UTC, spark-sse commented on apps/site/pages/dashboard/index.tsx
> +}
kannst du das jetzt noch einmal mit dem feat/ltb/master mergen und das dann in die library schieben?

2024-10-14 13:27 UTC, spark-sse commented
#192