fix(LearningDiary): Allows multiple strategies to be rated
e-Learning-by-SSE/nm-self-learning pull request #212
Opened 2024-10-07 12:17 UTC by palfner-sse

2024-10-08 08:23 UTC, spark-sse requested changes
passt. bitte einmal kontrollieren ob das formatting passt. 

und das onChange als eigene methode auslagern wäre sinnvoll. Ansonsten kann das so bleiben

2024-10-22 12:52 UTC, spark-sse commented
wie siehts hier aus?

2024-10-22 13:09 UTC, palfner-sse commented
Sag du es mir, hab ein Rereview angefordert. Ich bin damit fertig.

2024-10-22 13:15 UTC, palfner-sse commented
Ich dachte eigentlich, das wird im Board automatisch verschoben, wenn ich den Button drücke.

2024-10-22 13:19 UTC, spark-sse approved these changes

2024-10-22 15:43 UTC, merged

2024-10-27 12:46 UTC, spark-sse commented
lohnt jetzt nicht mehr zurückzurverfolgen ob da ein automatismus kaputt war oder sonst iwas schief gelaufen ist. 

Läuft ja jetzt und is auch gemerged. 

Wir schauen einfach ob es da öfter zu problemen kommt oder nicht.