Fix/dashboard bugs
e-Learning-by-SSE/nm-self-learning pull request #220
Opened 2024-10-14 10:55 UTC by staciwamonika

dashboard:
- fixed bug: when toggle “Lerntagebuch” is switch to “off” the “Kursübersicht” disappears
- rf: position of cog
- rf: when toggle "LTB" on the toggle "Lernstatistiken" automatically on

learning diary entry page
-  Sidebar is now "glued" to diary entry (all elements centric)

2024-10-14 12:54 UTC, spark-sse commented on apps/site/pages/dashboard/index.tsx
> +
debug?

2024-10-14 12:54 UTC, spark-sse commented on apps/site/pages/dashboard/index.tsx
> +										{completion.course?.title} ajlksdjflak
typo?

2024-10-14 12:54 UTC, spark-sse commented on libs/feature/settings/src/lib/settings-dialog/student-settings-dialog.tsx
> +	}, [settings.hasLearningDiary]);
bitte noch einmal einen weg ohne useEffect suchen. Der Wert kann direkt aus einem bestehenden state abgeleitet werden. 

Erhöht so die komplexität der methode

2024-10-16 15:23 UTC, staciwamonika commented on apps/site/pages/dashboard/index.tsx
> +
yes :)

2024-10-16 15:23 UTC, staciwamonika commented on apps/site/pages/dashboard/index.tsx
> +										{completion.course?.title} ajlksdjflak
yes, indeed

2024-10-16 15:24 UTC, staciwamonika commented on libs/feature/settings/src/lib/settings-dialog/student-settings-dialog.tsx
> +	}, [settings.hasLearningDiary]);
removed useEffect

2024-10-28 12:15 UTC, spark-sse requested changes

2024-11-11 13:50 UTC, staciwamonika commented on apps/site/pages/dashboard/index.tsx
> +		})
done

2024-11-11 13:50 UTC, staciwamonika commented on apps/site/pages/dashboard/index.tsx
> +	const lessonsFromDiary: any[] = student.learningDiaryEntrys.flatMap(entry =>
changed to type DiaryLessonSchema

2024-11-11 13:51 UTC, staciwamonika commented on apps/site/pages/dashboard/index.tsx
> +async function getTouchedLessons(student: Student, numOfLessons: number) {
done

2024-11-15 15:02 UTC, spark-sse approved these changes

2024-11-15 15:10 UTC, merged