[Quiz] Fehlender "Zur nächsten Lerneinheit" Button bei Quiz-Fehlversuch
e-Learning-by-SSE/nm-self-learning pull request #226
Opened 2024-10-30 15:52 UTC by palfner-sse

closes #199 
closes #189

2024-11-02 21:30 UTC, spark-sse commented
dafür hätte ich gerne einen test. 

Für die Konzeption davon können wir uns zusammen setzen. Es sind noch nicht alle Beispiele für UI-Tests hochgeladen

2024-11-04 10:05 UTC, palfner-sse commented
Alles klar. Lass uns um 13 Uhr ein Termin finden.

2024-11-15 18:24 UTC, spark-sse requested changes

2024-11-15 18:24 UTC, spark-sse commented on apps/site/__tests__/quiz.spec.tsx
> +	it("should not open any dialog", () => {
die testfälle sollten auich das setup beinhalten. 

zB "It should not open completion-dialog when completionState is in progress"

Also auch die conditions. Das gilt für alle Testfälle.

Ansonsten gute erste tests!

2024-11-15 18:52 UTC, spark-sse commented
Bei den Tests kommt folgende Meldung 


```
console.error
    Warning: An update to TransitionRootFn inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at [https://reactjs.org/link/wrap-tests-with-act](https://reactjs.org/link/wrap-tests-with-act%1B[39m)
        at fn (/home/jenkins/workspace/Teaching_nm-self-learn_PR-226@2/node_modules/@headlessui/react/dist/headlessui.dev.cjs:8598:9)
        at fn (/home/jenkins/workspace/Teaching_nm-self-learn_PR-226@2/node_modules/@headlessui/react/dist/headlessui.dev.cjs:7969:3)
        at fn (/home/jenkins/workspace/Teaching_nm-self-learn_PR-226@2/node_modules/@headlessui/react/dist/headlessui.dev.cjs:8859:21)
        at fn (/home/jenkins/workspace/Teaching_nm-self-learn_PR-226@2/libs/ui/common/src/lib/dialog/dialog.tsx:7:2)
        at fn (/home/jenkins/workspace/Teaching_nm-self-learn_PR-226@2/apps/site/pages/courses/[courseSlug]/[lessonSlug]/quiz.tsx:377:2)
        at div
        at fn (/home/jenkins/workspace/Teaching_nm-self-learn_PR-226@2/apps/site/pages/courses/[courseSlug]/[lessonSlug]/quiz.tsx:170:2)
```

2024-11-15 22:21 UTC, spark-sse commented
hab die änderungen fix selber gemacht. 
@palfner-sse bitte meine letzten beiden commits mal anschauen.

2024-11-15 22:22 UTC, spark-sse approved these changes

2024-11-15 22:23 UTC, merged