Feat/37 latex markdown support for clozes
e-Learning-by-SSE/nm-self-learning pull request #75
Opened 2023-10-25 09:47 UTC by lukas-png

Ich hatte diesen Branch noch von dev gezogen. Da der dev noch nicht final in den master gemerged ist, habe ich den pull request noch auf den dev gezielt

2023-10-25 09:49 UTC, lukas-png commented
#37

2023-11-02 10:12 UTC, spark-sse requested changes

2023-11-02 16:22 UTC, lukas-png commented on libs/feature/question-types/src/lib/question-types/cloze/cloze-parser.spec.ts
> -	describe("parseNextGap", () => {
Ich kann gerne neue Tests schreiben. Der Grund für die Löschung war, dass die Funktion parseNextGap nicht mehr benötigt und dementsprechend gelöscht wurde. Deshalb hatte ich auch den Test dafür gelöscht.

2023-11-02 17:30 UTC, spark-sse commented
**Beim Anwendertest wurde ein Fehler gefunden:** 

Darstellungsfehler beim erstellen eines Lückentexts:
Je nach freistehenden Leerzeichen, tauchen Fragmente hinter dem Lückentext auf. 
![grafik](https://github.com/e-Learning-by-SSE/nm-self-learning/assets/113825305/82a30f41-32d1-4348-826a-887312f66701)


Im obigen Beispiel sind drei Leerzeichen, die zu `$]}` führen. Ein Leerzeichen führt zu `}`, zwei zu `]`

2023-11-05 10:47 UTC, lukas-png commented
> **Beim Anwendertest wurde ein Fehler gefunden:**
> 
> Darstellungsfehler beim erstellen eines Lückentexts unter Verwendung des vorhandenen Beispiels: Je nach freistehenden Leerzeichen, tauchen Fragmente hinter dem Lückentext auf. ![grafik](https://user-images.githubusercontent.com/113825305/280076894-82a30f41-32d1-4348-826a-887312f66701.png)
> 
> Im obigen Beispiel sind drei Leerzeichen, die zu `$]}` führen. Ein Leerzeichen führt zu `}`, zwei zu `]` Zusätzlich sind Elemente vom vorherigen Text nicht mehr erkennbar. (Hier `BodyStart`)

Es wäre sehr hilfreich, wenn du den Code, der den Fehler verursacht, direkt in deiner Nachricht einfügen könntest. Dann kann ich den Bug leichter nachvollziehen und ausschließen, dass es an einem Tippfehler liegt

2023-11-23 10:13 UTC, lukas-png commented
@spark-sse die sachen sind geändert

2023-12-04 14:23 UTC, merged