Feat/62 sperren von inhalten für nicht angemeldete nutzer
e-Learning-by-SSE/nm-self-learning pull request #86
Opened 2023-11-10 15:54 UTC by staciwamonika

2023-11-27 10:36 UTC, spark-sse requested changes
Derzeit fehlende Funktionalität: Nutzende (ohne Anmeldung) können noch auf Lerneinheiten zugreifen. Z.B. im default seed: http://localhost:4200/courses/objectorientierte-programmierung-mit-java

2023-11-27 10:36 UTC, spark-sse commented on apps/site/pages/courses/[courseSlug]/index.tsx
> +function useSessionInfo() {
non suiting method name. Suggestion is a more descriptive method name like isUserAuthenticatedInSession()

2023-11-27 10:36 UTC, spark-sse commented on apps/site/pages/courses/[courseSlug]/index.tsx
> +	const userAuthenticated = useSessionInfo();
other variables in this method which have a boolean state start with "is.."

2023-11-27 10:36 UTC, spark-sse commented on apps/site/pages/courses/[courseSlug]/index.tsx
> +
quasi duplicate code.

evtl authentication check in onClick verlagern? So könnte dort eine überprüfung stattfinden. 
Beispiel: 
```ts
	const enrollOrRedirect = () => {
		if (isUserAuthenticatedInSession) {
			enroll({ courseId: course.courseId });
		} else {
			redirectToLogin();
		}
	};
```

`onClick={enrollOrRedirect}`

2023-12-19 15:41 UTC, spark-sse commented
Erreichen der Webseiten via Direktlink noch möglich. Änderungen notwendig. 
Möglicherweise ist die verwendung von AuthorizedGuard in der `guard.ts` sinnvoll. .

2024-07-16 08:12 UTC, staciwamonika commented on libs/feature/authentication/authentication.ts
resolved this issue with b5d1aa5

2024-07-16 08:33 UTC, staciwamonika commented on apps/site/pages/courses/[courseSlug]/index.tsx
> +	function handleClick() {
resolved with df92f2d

2024-12-06 17:11 UTC, closed without merging