Feat/68 zyklische abhängigkeiten innerhalb der skillmodellierung den autoren anzeigen
e-Learning-by-SSE/nm-self-learning pull request #94
Opened 2023-11-30 13:58 UTC by lukas-png

#68

2023-12-12 14:03 UTC, spark-sse requested changes
War jetzt nur ein Teil der Reviewed wurde. Die fehlerhaften Linting Einstellungen haben das erschwert.

Ein weiterer Review wird auch noch erfolgen sobald es im nächsten Feature-Branch ist.

2023-12-12 14:03 UTC, spark-sse commented on libs/feature/teaching/src/lib/skills/skill-dialog/select-skill-dialog.tsx
> +import { memo, useEffect, useState } from "react";
?

2023-12-12 19:55 UTC, lukas-png commented on libs/feature/teaching/src/lib/skills/folder-editor/cycle-detection/detection-hook.tsx
> +const memorizedDetection: FolderItem[] = [];
Kannst du dein Problem näher spezifizieren

2023-12-12 19:55 UTC, lukas-png commented on apps/site/pages/skills/repository/[repoSlug]/index.tsx
> +	if (!repoId || repoId === "") return {notFound: true}
Was stört dich genau daran ? Das if statement ist recht komplex. Das kann man auf jedenfall kürzen. Man kann auch von einer statischen weiterleitung auf eine dynamische umsteigen

2023-12-13 13:51 UTC, spark-sse commented on libs/feature/teaching/src/lib/skills/folder-editor/folder-list-view.tsx
> +	const [, setAddChildren] = useState<SkillFormModel | null>(null);
Oh,da war ich etwas sparsam mit worten. Mir ging es nicht um den syntax, sondern um die Frage, warum hier lediglich ein setter verwendet wird. Ist irgendwo ein shared state? Oder wird das nur verwendet um die komponente zu neurendern zu nutzen? dafür hätte ich ein anderes vorgehen erwartet.

2023-12-13 14:02 UTC, spark-sse commented on apps/site/pages/skills/repository/[repoSlug]/index.tsx
> +	if (!repoId || repoId === "") return {notFound: true}
beim überfliegen hab ich die negation am anfang des if statements nicht gesehen. 

Dann kommt die Folgefrage: Hier wird auf eine valide session geprüft. hierfür einen globalen guard. Wurde der vergessen oder kann der hier aus Gründen nicht angewendet werden?

2023-12-13 18:15 UTC, spark-sse commented on libs/feature/teaching/src/lib/skills/folder-editor/cycle-detection/detection-hook.tsx
> +const memorizedDetection: FolderItem[] = [];
- global state management (also mit globalen variablen) ist kein gutes vorgehen. Am besten das react state management benutzen - wenn notwendig - wie zB `useContext` und `createContext`. Eventuell kann man das aber auch mit methodenaparametern lösen?
- ein variablen name sollte `memorized` nur beinhalten, wenn auch die entsprechende react funktionalität verwendet wird (zB `useMemo`)

2023-12-13 18:17 UTC, spark-sse commented on libs/feature/teaching/src/lib/skills/folder-editor/cycle-detection/detection-hook.tsx
> +export const ClearCycleDetection = () => {
methodenname sollte in lower camel case geschrieben werden, sofern es sich nicht um eine react komponente handelt.

2023-12-14 10:50 UTC, spark-sse commented on apps/site/pages/skills/repository/[repoSlug]/index.tsx
> +	if (!repoId || repoId === "") return {notFound: true}
guards sind client-side. Hilfsmethoden werden zukünftig verwendet um session checks zu vereinfachen

2023-12-14 11:11 UTC, spark-sse commented on libs/feature/teaching/src/lib/skills/folder-editor/skill-taskbar.tsx
> +				};
in skill.router.ts ist ein resolved und unresolved typ für die skills. 


```
export type SkillResolved = ResolvedValue<typeof getSkillById>;
export type SkillUnresolved = Omit<SkillResolved, "children" | "repository" | "parents">;
```

2024-01-04 11:50 UTC, spark-sse commented
Es wurde sich auf ein Refactoring der `dispatchDialog` und `dispatchDetection` geeinigt. Es werden nicht mehr etablierte React-Pattern genutzt sondern eigene Infrastrukturen gebaut (u.A. mit einem module-scope storage via globale variabeln). Insbesondere führt es zu weniger Reusability (es werden keine Komponenten mehr erstellt), wie auch testen ist schwierigier. Es ist zwar funktionstüchtig, weicht aber zu stark vom bisherigen Vorgehen in der Code-Basis ab.

2024-02-08 12:40 UTC, merged