Feat/53 search function
e-Learning-by-SSE/nm-self-learning pull request #99
Opened 2023-12-08 12:12 UTC by Arne1303

Closes #53

2024-01-03 12:43 UTC, spark-sse requested changes
gut! allerdings müsste die SearchBar komponente stärker modularisiert werden

2024-01-08 08:37 UTC, Arne1303 commented on libs/feature/teaching/src/lib/course/course-info-form.tsx
Scheinen die line endings zu sein, ich werde das amenden und die Änderungen an der Datei verwerfen, inhaltlich ist da nichts passiert. Dann ist der git Verlauf etwas sauberer

2024-01-08 08:51 UTC, Arne1303 commented on libs/ui/layouts/src/lib/search-bar.tsx
> +	}, [searchQuery]);
Ne hat er nicht mehr, nehm ich raus

2024-01-08 09:00 UTC, Arne1303 commented on libs/ui/layouts/src/lib/search-section.tsx
> +				{results.slice(0, 4).map(result => (
Ich mach props mit defaults draus, dann können die bei Wiederverwendung auch noch geändert werden

2024-01-08 09:43 UTC, Arne1303 commented
> gut! allerdings müsste die SearchBar komponente stärker modularisiert werden

@spark-sse Kannst du mir ein Beispiel geben in welchem anderen Kontext die SearchBar verwendet werden könnte/was daran modulierbar sein soll?

2024-02-16 16:00 UTC, spark-sse commented
Wenn unklar ist wo sie eingesetzt werden kann, dann sollten die komponenten als layout komponenten behandelt werden. d.h. für die komponente selber ist es unwichtig wo sie aufgerufen wird. 

Ich habe jetzt erstmal leichte strukturänderungen vorgenommen um die lesbarkeit und wartbarkeit etwas zu fördern. Auf resuabiility kann man das zukünftig setzen.

2024-02-16 16:01 UTC, merged